# Generated by Django 4.0.6 on 2022-07-27 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Type',
        ),
        migrations.RemoveField(
            model_name='product_review',
            name='rating',
        ),
    ]
