# Generated by Django 4.0.6 on 2022-07-27 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_type_remove_product_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mataTitle',
            new_name='metaTitle',
        ),
    ]
