# Generated by Django 4.0.6 on 2022-07-27 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionId', models.CharField(default='', max_length=100)),
                ('token', models.CharField(default='', max_length=100)),
                ('status', models.IntegerField(max_length=6)),
                ('fistName', models.CharField(default='', max_length=50)),
                ('middleName', models.CharField(default='', max_length=50)),
                ('lastName', models.CharField(default='', max_length=50)),
                ('mobile', models.CharField(default='', max_length=15)),
                ('email', models.CharField(default='', max_length=50)),
                ('line1', models.CharField(default='', max_length=50)),
                ('line2', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('province', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='cart_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='', max_length=100)),
                ('price', models.FloatField(default='')),
                ('discount', models.FloatField(default='')),
                ('quantity', models.IntegerField(default='', max_length=6)),
                ('active', models.IntegerField(max_length=1)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(default='')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
            ],
        ),
    ]
