# Generated by Django 4.0.6 on 2022-07-27 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
        migrations.RemoveField(
            model_name='cart_item',
            name='active',
        ),
        migrations.RemoveField(
            model_name='cart_item',
            name='quantity',
        ),
    ]
