# Generated by Django 4.0.6 on 2022-08-12 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_admin_remove_user_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passwordHash',
        ),
    ]
