# Generated by Django 4.0.6 on 2022-07-27 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
    ]
